.eslintrc.js
package.json

Add coding style setting and a blank front end javascript file

Add coding style setting and a blank front end javascript file

---

controllers/usersController.js
public/javascripts/scripts.js
public/stylesheets/styles.css
views/layouts/main.hbs

- Add login message (flash)
- Add toast message function for login/logout

Feature flash message

---

controllers/adminController.js
controllers/usersController.js
models/user.js
public/stylesheets/styles.css
routes/index.js
views/admin.hbs
views/login.hbs
views/partials/column_adminNav.hbs
views/partials/column_adminTweets.hbs
views/partials/column_adminUsers.hbs

Trello cards 
[1](https://trello.com/c/5jd9P7hG) 
[2](https://trello.com/c/2LQKaka4)
[3](https://trello.com/c/aWe3Vc53)
[4](https://trello.com/c/af7QJhqo)
[5](https://trello.com/c/cfqL8evS)
完成功能如下

Feature admin portal

---

middleware/authenticationHelper.js
routes/index.js
routes/modules/users.js

Add access restriction to users and admins

---

config/passport.js
controllers/likesController.js
controllers/tweetsController.js
models/like.js
models/user.js
routes/index.js
routes/modules/likes.js
views/partials/column_main.hbs

Feature likes

---

config/passport.js
controllers/usersController.js
models/reply.js
models/tweet.js
public/stylesheets/styles.css
routes/modules/users.js
views/partials/column_main.hbs
views/partials/column_main_user.hbs
views/partials/column_nav.hbs
views/partials/listitem_tweet.hbs

User's own liked tweets list

---

config/handlebars-helpers.js
controllers/usersController.js
package-lock.json
package.json
public/stylesheets/styles.css
routes/modules/users.js
views/layouts/main.hbs
views/partials/column_main.hbs
views/partials/column_main_user.hbs
views/partials/listitem_noitem.hbs

Feature user self

---

controllers/tweetsController.js
public/stylesheets/styles.css
routes/index.js
routes/modules/tweets.js
views/partials/column_main.hbs
views/partials/listitem_reply.hbs
views/partials/listitem_tweet.hbs

[trello卡片](https://trello.com/c/f5xZPCIO/7-%E9%BB%9E%E6%93%8A%E8%B2%BC%E6%96%87%E6%96%B9%E5%A1%8A%E6%99%82%EF%BC%8C%E8%83%BD%E6%9F%A5%E7%9C%8B%E8%B2%BC%E6%96%87%E8%88%87%E5%9B%9E%E8%A6%86%E4%B8%B2)
- 點擊單一tweet可以進入詳細頁，詳細頁內可以瀏覽tweet資料和reply list
未解決問題:
1. 目前是直接開新的listitem_reply.hbs渲染畫面，右側"跟隨誰"會抓不到資料
2. tweet詳細頁的發文時間格式尚未修改 (要改成例如" 上午 10:05・2020年6月10日 "的格式)

Feature reply list

---

controllers/tweetsController.js
routes/index.js
routes/modules/tweets.js
views/partials/listitem_reply.hbs
views/partials/listitem_tweet.hbs

- 新增回覆功能，使用者送出空白回覆會回覆失敗並跳訊息提示，回覆字數超過140字時回覆按鈕會inactive [Trello1](https://trello.com/c/cfdEvAiv/8-%E4%BD%BF%E7%94%A8%E8%80%85%E8%83%BD%E5%9B%9E%E8%A6%86%E5%88%A5%E4%BA%BA%E7%9A%84%E6%8E%A8%E6%96%87%EF%BC%8C%E5%9B%9E%E8%A6%86%E6%96%87%E5%AD%97%E4%B8%8D%E8%83%BD%E7%82%BA%E7%A9%BA%E7%99%BD%EF%BC%9B%E8%8B%A5%E4%B8%8D%E7%AC%A6%E5%90%88%E8%A6%8F%E5%AE%9A%EF%BC%8C%E6%9C%83%E8%B7%B3%E5%9B%9E%E5%90%8C%E4%B8%80%E9%A0%81%E4%B8%A6%E9%A1%AF%E7%A4%BA%E9%8C%AF%E8%AA%A4%E8%A8%8A%E6%81%AF)
- 修改reply有關的router
- 改用Moment.js呈現推文時間 [trello2](https://trello.com/c/zAyUVbW8/61-%E9%BB%9E%E6%93%8A%E8%B2%BC%E6%96%87%E6%96%B9%E5%A1%8A%E6%99%82%EF%BC%8C%E8%83%BD%E6%9F%A5%E7%9C%8B%E8%B2%BC%E6%96%87%E8%88%87%E5%9B%9E%E8%A6%86%E4%B8%B2%EF%BC%8C%E6%99%82%E9%96%93%E6%A0%BC%E5%BC%8F%E5%98%97%E8%A9%A6%E7%94%A8-moment)
UI問題 …

Feature reply

---

config/handlebars-helpers.js
controllers/usersController.js
views/partials/column_main_user.hbs

[Trello 卡片](https://trello.com/c/khy1wYax/15-%E4%BB%BB%E4%BD%95%E7%99%BB%E5%85%A5%E4%BD%BF%E7%94%A8%E8%80%85%E9%83%BD%E5%8F%AF%E4%BB%A5%E7%80%8F%E8%A6%BD%E7%89%B9%E5%AE%9A%E4%BD%BF%E7%94%A8%E8%80%85%E7%9A%84%E4%BB%A5%E4%B8%8B%E8%B3%87%E6%96%99%E9%9D%9Emodal%EF%BC%8C%E4%B8%AD%E9%96%93%E6%AC%84)
- 更新個人用戶頁面，本人與非本人用戶頁面出現不同按鈕及作用。

Feature main_user page buttons

---

controllers/followshipController.js
routes/index.js
routes/modules/followships.js
views/partials/listitem_user.hbs

- rename following routes from following to followship
- add router.post('/'.....) to handle test auto submission
- followship controller add extra handling for both req.params.id and req.body.id
- followship controller add redirect status for failed following
- update user list follow action url

Refactor: fixes to accomodate followships mocha test

---

_helpers.js
controllers/usersController.js
custom_helpers.js
public/stylesheets/styles.css
views/partials/column_main_user.hbs

[Trello 卡片](https://trello.com/c/GkaZTa6r/67-imgur-api-helpers-move-to-services-helpers)

refactor: uploadFile service

---

controllers/tweetsController.js
public/stylesheets/styles.css
views/partials/column_main.hbs
views/partials/column_main_tweet.hbs
views/partials/listitem_reply.hbs

- Reply list to sort desc by createAt
- re-mapped reply hbs templating to match the rest of the site
- Add cool actual twitter style like and reply button, reckon it looks cool, please contact shaunwhl1991@gmail.com if you believe this has violated any rights.
- change getUserDetails to helpers.getUser because likedTweets is being set in req.user var, as it is fairly lightweight.

Feature reply UI

---

public/stylesheets/styles.css
views/partials/column_main_user.hbs

UI improvement
[Trello 卡片](https://trello.com/c/PuzsFqUa/57-%E7%B7%A8%E8%BC%AF%E5%80%8B%E4%BA%BA%E8%B3%87%E6%96%99-%E7%89%88%E5%9E%8B%E8%AA%BF%E6%95%B4)

Feature self edit modal

---

controllers/usersController.js
public/stylesheets/styles.css

- Following now sorting by new ones at top
- Fix following list avatar issue

Following sorting fix

---

controllers/likesController.js
controllers/tweetsController.js
routes/modules/tweets.js

- adjusted like controller to handle user details differently
- add post route handling for unlike
- add empty likedTweets handling for test user

Tweet spec adjustment

---

controllers/api/usersController.js
controllers/usersController.js
routes/index.js
routes/modules/apis.js
services/usersService.js
views/partials/column_main_user.hbs

- refactor usersController to match mocha user test
- create usersController API & usersService
- refactor userController #getUser #putUser 
- refactor user edit page following button route 
pass user.spec test

Refactor user test

---

controllers/usersController.js
middleware/authenticationHelper.js
routes/index.js

- fix endless likes bug caused by likedTweets missing
- optimised getUserDetails by removing large sql query (functions will need to use promise calls to get individual details async to improve performance)
- Optimised user's tweets page, tweets and replies page, and liked tweets page
- update getUserLikedTweets helper to return tweets sorted by liked date time
- normal user redirect to normal login page after failed admin portal login attempt

Bugbuster basefunctions

---

controllers/usersController.js
public/stylesheets/styles.css
views/partials/column_main.hbs
views/partials/column_main_user.hbs
views/partials/column_nav.hbs
views/partials/column_setting.hbs
views/partials/listitem_user.hbs

[Trello 卡片 註冊帳號有預設 cover 圖，但沒有預設大頭照](https://trello.com/c/dV9TbgTI/49-bug-%E8%A8%BB%E5%86%8A%E5%B8%B3%E8%99%9F%E6%9C%89%E9%A0%90%E8%A8%AD-cover-%E5%9C%96%EF%BC%8C%E4%BD%86%E6%B2%92%E6%9C%89%E9%A0%90%E8%A8%AD%E5%A4%A7%E9%A0%AD%E7%85%A7)
[Trello 卡片](https://trello.com/c/LSWinnPC/56-%E5%A4%A7%E9%A0%AD%E7%85%A7%E3%80%81%E8%B7%9F%E9%9A%A8%E6%8C%89%E9%88%95-%E5%B0%BA%E5%AF%B8%E4%BF%AE%E6%AD%A3)
[Trello 卡片](https://trello.com/c/PuzsFqUa/57-%E7%B7%A8%E8%BC%AF%E5%80%8B%E4%BA%BA%E8%B3%87%E6%96%99-%E7%89%88%E5%9E%8B%E8%AA%BF%E6%95%B4)
- 註冊新帳號給予用戶隨機 avator 和 cover 圖檔
- 跟隨、正在跟隨、推文、儲存 按鈕調整
- 個人資料編輯 UI 調整

Bug register ＆ UI improvement 

---

controllers/api/tweetsController.js
controllers/tweetsController.js
public/javascripts/scripts.js
public/stylesheets/styles.css
routes/modules/apis.js
views/layouts/main.hbs
views/partials/column_main.hbs
views/partials/column_main_tweet.hbs
views/partials/column_nav.hbs
views/partials/listitem_tweet.hbs

- 新增api提供reply modal需要的資料
- 回覆成功時原本會跳回tweet詳細頁，已修改成返回原畫面(比較直覺)

feat: add reply api for reply modal

---

app.js
public/javascripts/socket.js

Chatroom disconnecting

---

app.js
controllers/chatsController.js
controllers/tweetsController.js
migrations/20210312121809-create-message.js
models/message.js
package.json
public/javascripts/socket.js
public/stylesheets/styles.css
routes/index.js
routes/modules/chatroom.js
views/chatroom.hbs
views/layouts/main.hbs
views/partials/column_chatroom_main.hbs
views/partials/column_chatroom_side.hbs
views/partials/column_nav.hbs
views/partials/listitem_onlineUser.hbs

- Challenge 1 basically done, except for a few UI tweaks
- public chatroom with real-time messaging
- public chatroom chat history will be saved

Chatroom level1

---

public/javascripts/socket.js

fix showing notification badge issue even with no notification left

fix showing notification badge issue even with no notification left
